# A program to store vocabulary while learning or practicing a new language.

First, I define a help function `countWords` to determine whether an entry has one, two, or more words.
To test it, I use the array `my_words`.

In [11]:
my_words = ['abarbeiten', 'die Wertschöpfung', 'etwas in Worte fassen']

def countWords(text):
  if len(text) == 0:
    return 0
  words = 1
  for letter in text:
    if letter == ' ' and text[0] != letter and text[-1] != letter:
      words += 1
  return words

for i in my_words:
    print(countWords(i))

1
2
4


I use the `json` library to create my vocabulary list.

In [16]:
import json

## Description of my classes

1. `Entry`. It has three attributes:
    1. `Text`.
    5. `Date`.
    4. `Category`.
3. `Noun`. A subclass of `Entry`, it has one additional attribute:
    * `Article`.
50. `Dictionary`. It has the following properties:
    + It consists of entries. Those are stored in a JSON file whose path is given to the constructor.
    + Should be able to add entries.
    + It should allow the filtering of the whole list and create sublists using different criteria.

Remark: an `entry` might be a word or a sentence (e.g. a common idiom).

In [39]:
class Entry:
  def __init__(self, text, date, category):
    self.text = text
    self.date = date
    self.category = category
  def __str__(self):
    return self.text
  def __repr__(self):
    return f"{self.text}"

class Noun(Entry):
  def __init__(self, article, text, date, category):
    super().__init__(text, date, category)
    self.article = article
  def __repr__(self):
    return f"{self.article} {self.text}"



In [41]:
# Codigo Clase Diccionario
class Dictionary:
  def __init__(self, file_path):
    self.file_path = file_path
    self.list = self.crear_list()

  def crear_list(self):
    with open(self.file_path, 'r') as file:
      my_entries = json.loads(file.read())
      #print(mis_entradas)
      entries_categorized = []
      for entry in my_entries["Entradas"]:
        #print(entrada["palabra"])
        if countWords(entry["palabra"]) == 2:
          entries_categorized.append(Noun(article=entry["palabra"][0:3], text=entry["palabra"][4:], date=entry["fecha"], category="Noun"))
        else:
          entries_categorized.append(Entry(text=entry["palabra"], date=entry["fecha"], category="Other"))
      return entries_categorized


In [164]:
class VocabularyList:
  def __init__(self, vocab_list):
    self.vocab_list = vocab_list
    self.table = self.create_table()
    
# Create the tabla using the entries in the the dictionary
  def create_table(self):
    numbering = []
    vocabulary = []
    i = 1
    entry_i = "Entry "
    for entry in self.vocab_list:
      numbering.append(entry_i + str(i))
      # TODO: add something to deal with wrong entries
      show_date = f'{entry.date[0]}-{entry.date[1]}-{entry.date[2]}'
      list_row = [entry.__repr__(), show_date, entry.category]
      vocabulary.append(list_row)
      i += 1
    return vocabulary, numbering, ["", "Text", "Date", "Category"]

# Function to show a well-ordered table with my vocabulary   
  def show_table(self, vocabulary, enumeration, columns):
    # TODO: here, I have to complete the function specifying the desired format
    print("{:<10} {:<20} {:<12} {:<12}".format(*columns))
    # TODO: here handle with the case that enumeration and vocabulary have different lengths
    for i in range(len(vocabulary)):
        print("{:<10} {:<20} {:<12} {:<12}".format(enumeration[i], *vocabulary[i]))
    


In [166]:
#def isSustantivo(entrada):
 #  if contarPalabras(entrada.texto) == 2:
  #    return true

# esta es la función que filtrará las tablas y entrega los resultados
#def filtrarTabla(tabla, criterio, valor):
    #match criterio:
      #case "categoria": return filtrarCategoria(tabla, valor)
      #case "letra_inicial": return filtrarLetraInicial(tabla, valor)
      #case _: return "Para tal criterio no hay nada aun"

#def filtrarCategoria(tabla, valor):
    #tabla_filtrada = tabla.copy()
    #match valor:
      #case "Sustantivo" | "Otra": return tabla_filtrada.loc[lambda df: df["Categoria"] == valor, :]
      #case _: return "Categoría inválida."

#def filtrarLetraInicial(tabla, valor):
    #tabla_filtrada = tabla.copy()
    #if len(valor) != 1:
      #return "Ingresar solamente una letra."
    #valor = valor.lower()
    #for i in tabla.loc[:,"Palabra"]:
      #if contarPalabras(i) == 2 and i[4] != valor.capitalize():
        #idx = tabla.index[tabla["Palabra"]==i].tolist()
        #tabla_filtrada = tabla_filtrada.drop(idx)
      #elif contarPalabras(i) == 1 and i[0] != valor:
        #idx = tabla.index[tabla["Palabra"]==i].tolist()
        #tabla_filtrada = tabla_filtrada.drop(idx)
    #return tabla_filtrada


In [168]:
new_dict = Dictionary("entradas_reducidas.json")
my_entries = new_dict.list
print(my_entries)
#print(nuevo_diccionario.listado[0].fecha)
#print(nuevo_diccionario.listado[0].__str__())
#print(nuevo_diccionario.listado[1].__repr__())
#print(nuevo_diccionario.listado[1].articulo)

[abarbeiten, abfangen, die Abfolge, abgelten, abgrenzen, die Besteuerung, bestmoeglich, bewirten, durchreichen, einheitlich, einordnen, der Einsatz, einsortieren, entbehrlich, das Entgelt, entkoppeln, das Fachkonzept, fachlich, die Fachlichkeit, die Festlegung, das Formelwerk, foermlich, gegenueberstellen, misslingen, nachgelagert, nahelegen, niederdruecken, notduerftig, die Plausibilisierung, raushauen, die Rechnungslegung, die Rentenperiode, das Tafelwerk, ungemein, unterlassen, unuebersichtlich, unzulaenglich, verbindlich, verkomplizieren, verschaffen, vervollstaendigen, die Verweildauer, der Vorgang, das Vorhaben, vorlaeufig, der Zeitwert, zusammensetzen, der Zusatz, die Zustaendigkeit, die Zusicherung, zuweisen, zwangslaeufig]


In [170]:
newTable = VocabularyList(mis_entradas)
#print(nueva_tabla.tabla)
entries, enums, cols = newTable.create_table()
print(cols[2])
newTable.show_table(entries, enums, cols)

Date
           Text                 Date         Category    
Entry 1    abarbeiten           29-11-2022   Other       
Entry 2    abfangen             24-5-2023    Other       
Entry 3    die Abfolge          12-12-2022   Noun        
Entry 4    abgelten             28-12-2022   Other       
Entry 5    abgrenzen            24-5-2023    Other       
Entry 6    die Besteuerung      7-12-2022    Noun        
Entry 7    bestmoeglich         13-12-2022   Other       
Entry 8    bewirten             29-12-2022   Other       
Entry 9    durchreichen         13-12-2022   Other       
Entry 10   einheitlich          21-12-2022   Other       
Entry 11   einordnen            14-12-2022   Other       
Entry 12   der Einsatz          15-12-2022   Noun        
Entry 13   einsortieren         4-1-2023     Other       
Entry 14   entbehrlich          28-12-2022   Other       
Entry 15   das Entgelt          7-12-2022    Noun        
Entry 16   entkoppeln           28-12-2022   Other       
Entry 17 

In [70]:
#filtrarTabla(tabla_entradas, "letra_inicial", "F")

## Next steps:

- Filter using different criteria:
  1. Alphabetic
  2. Date
  3. Category
- Add vocabulary into the JSON file.

In [157]:
pd.read_json('entrada_simple.json', orient="records")

entrada           fecha
0   abarbeiten  [29, 11, 2022]
1  die Abfolge  [12, 12, 2022]

In [22]:
import numpy as np

index = pd.date_range("1/1/2000", periods=8)

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])
print(np.random.randn(8, 3) )
print(df)

[[ 9.41910128e-01  7.90234512e-01 -2.18467175e-01]
 [-7.96855617e-01 -3.84789061e-01 -4.97087591e-01]
 [ 1.49431316e+00  7.57519435e-01 -5.85202887e-01]
 [ 3.05734161e-01 -4.19143336e-02  1.74862926e+00]
 [ 1.00568524e+00 -6.81190402e-04 -2.55177632e-01]
 [ 4.69615209e-01 -9.56371756e-01  2.06806276e+00]
 [-9.71785672e-01 -1.55651529e-01 -3.01620397e-01]
 [ 1.36386970e-01 -2.81418896e-01 -3.89706242e-01]]
                   A         B         C
2000-01-01 -2.759640 -0.312461 -0.548958
2000-01-02  1.206670  1.501298  2.315188
2000-01-03  0.849976  0.897112  0.074638
2000-01-04 -0.547975  2.160294 -0.046115
2000-01-05  1.968564 -0.067033 -0.363519
2000-01-06  0.062446  0.282341  0.233524
2000-01-07 -0.612508  0.259587  0.378447
2000-01-08  0.398564  0.736146 -1.216213


In [66]:
def reordenar(lista):
  lista[-1] = -5
  return lista

In [68]:
lista = [1,2,3,4]
reordenar(lista)
print(lista)

[1, 2, 3, -5]


In [181]:
p = "ab"
len(p)

2